### ISSUE TITLE
哈萨克斯坦不对，哈萨克斯坦国际电话区号变更为“+997”

### ISSUE THREAD

**Issue by lovemo** [BG7ZAG/country-code#8]
https://finance.sina.com.cn/tech/2021-09-21/doc-iktzscyx5514214.shtml

**Comment by lovemo** [comment]
用+7合理一些

**Comment by BG7ZAG** [comment]
是的，目前在用的是+7，已经更新了，感谢反馈
https://www.163.com/dy/article/HVREEJGD0552ZOBZ.html
https://www.huanenet.com/mtgd/7382.html
